namespace GenerateAst;

public class Generator(string baseName, string dir, string returnType, List<string> types)
{
    private readonly string baseName = baseName;
    private readonly string dir = dir;
    private readonly string returnType = returnType;
    private string ReturnTypeHelper => returnType == "void" ? "" : $"<{returnType}>";
    private readonly List<string> types = types;

    private void DefineBase()
    {
        string path = $"{dir}\\{baseName}.cs";

        // Delete the old file before generating the new one
        if (File.Exists(path))
        {
            Console.WriteLine($"Deleting {path}");
            File.Delete(path);
        }

        // Write to a new .cs file
        using StreamWriter sw = new(path, true);

        sw.WriteLine($"/// This file was autogenerated by LoxInterpreter/GenerateAst at {DateTime.Now:MM.dd.yy HH:mm:ss}.");
        sw.WriteLine();
        sw.WriteLine("namespace LoxInterpreter;");
        sw.WriteLine();

        // Write base class
        Console.WriteLine($"Writing class {baseName}()");
        sw.WriteLine($"public abstract partial class {baseName}()");
        sw.WriteLine("{");

        // Define IVisitor interface
        DefineIVisitor(sw);

        // Declare Accept method
        sw.WriteLine($"\tpublic abstract {returnType} Accept{ReturnTypeHelper}(IVisitor{ReturnTypeHelper} visitor);\n");

        // Write children classes
        foreach (string type in types)
        {
            string className = type.Split(":")[0].Trim();

            Console.WriteLine($"Writing class {className}()");
            string fields = type.Split(":")[1].Trim();
            DefineDerived(sw, className, fields);
        }

        sw.WriteLine("}\n");

        Console.WriteLine($"Generated {baseName}.cs with {types.Count} classes.");
    }

    private void DefineDerived(StreamWriter sw, string className, string fieldList)
    {
        // Add primary constructor
        sw.WriteLine($"\tpublic partial class {className}({fieldList}) : {baseName}()");
        sw.WriteLine("\t{");

        // Add private fields initialized by primary constructor
        string[] fields = fieldList.Split(", ");
        foreach (string field in fields)
        {
            string name = field.Split(" ")[1];
            string type = field.Split(" ")[0];
            sw.WriteLine($"\t\tprivate readonly {type} _{name.ToLower()} = {name};\n");
        }

        // Add public getters that return the private fields
        foreach (string field in fields)
        {
            string name = field.Split(" ")[1];
            string type = field.Split(" ")[0];
            sw.WriteLine($"\t\tpublic {type} {name} => _{name.ToLower()};\n");
        }

        // Implement Accept method
        sw.WriteLine($"\t\tpublic override {returnType} Accept{ReturnTypeHelper}(IVisitor{ReturnTypeHelper} visitor)\n\t\t{{");
        sw.WriteLine($"\t\t\t{(returnType == "void" ? "" : "return ")}visitor.Visit{className}{baseName}(this);");
        sw.WriteLine("\t\t}\n");

        sw.WriteLine("\t}\n");
    }

    private void DefineIVisitor(StreamWriter sw)
    {
        Console.WriteLine($"Writing interface IVisitor{ReturnTypeHelper}");

        sw.WriteLine($"\tpublic interface IVisitor{ReturnTypeHelper}\n\t{{");

        foreach (string type in types)
        {
            string className = type.Split(":")[0].Trim();
            sw.WriteLine($"\t\t{returnType} Visit{className}{baseName}({className} expr);\n");
        }
        sw.WriteLine("\t}\n");
    }

    public void Generate() => DefineBase();
}
