namespace GenerateAst;

class Program
{
    private static void DefineBase(string dir, string baseName, List<string> types)
    {
        string path = $"{dir}\\{baseName}.cs";

        // Delete the old file before generating the new one
        if (File.Exists(path))
        {
            Console.WriteLine($"Deleting {path}");
            File.Delete(path);
        }

        // Write to a new .cs file
        using StreamWriter sw = new(path, true);

        sw.WriteLine($"/// This file was autogenerated by LoxInterpreter/GenerateAst at {DateTime.Now:MM.dd.yy HH:mm:ss}.");
        sw.WriteLine();
        sw.WriteLine("namespace LoxInterpreter;");
        sw.WriteLine();

        // Write base class
        Console.WriteLine($"Writing class {baseName}()");
        sw.WriteLine($"public abstract partial class {baseName}()");
        sw.WriteLine("{");

        // Define IVisitor interface
        DefineIVisitor(sw, baseName, types);

        // Declare Accept method
        sw.WriteLine($"\tpublic abstract T Accept<T>(IVisitor<T> visitor);\n");

        // Write children classes
        foreach (string type in types)
        {
            string className = type.Split(":")[0].Trim();

            Console.WriteLine($"Writing class {className}()");
            string fields = type.Split(":")[1].Trim();
            DefineDerived(sw, baseName, className, fields);
        }

        sw.WriteLine("}\n");

        Console.WriteLine($"Generated {baseName}.cs with {types.Count} classes.");
    }

    private static void DefineDerived(StreamWriter sw, string baseName,
        string className, string fieldList)
    {
        // Add primary constructor
        sw.WriteLine($"\tpublic partial class {className}({fieldList}) : {baseName}()");
        sw.WriteLine("\t{");

        // Add private fields initialized by primary constructor
        string[] fields = fieldList.Split(", ");
        foreach (string field in fields)
        {
            string name = field.Split(" ")[1];
            string type = field.Split(" ")[0];
            sw.WriteLine($"\t\tprivate readonly {type} _{name.ToLower()} = {name};\n");
        }

        // Add public getters that return the private fields
        foreach (string field in fields)
        {
            string name = field.Split(" ")[1];
            string type = field.Split(" ")[0];
            sw.WriteLine($"\t\tpublic {type} {name} => _{name.ToLower()};\n");
        }

        // Implement Accept method
        sw.WriteLine($"\t\tpublic override T Accept<T>(IVisitor<T> visitor)\n\t\t{{");
        sw.WriteLine($"\t\t\treturn visitor.Visit{className}{baseName}(this);");
        sw.WriteLine("\t\t}\n");

        sw.WriteLine("\t}\n");
    }

    private static void DefineIVisitor(StreamWriter sw, string baseName, List<string> types)
    {
        Console.WriteLine($"Writing interface IVisitor<T>");

        sw.WriteLine($"\tpublic interface IVisitor<T>\n\t{{");

        foreach (string type in types)
        {
            string className = type.Split(":")[0].Trim();
            sw.WriteLine($"\t\tT Visit{className}{baseName}({className} expr);\n");
        }
        sw.WriteLine("\t}\n");
    }

    public static void Main(string[] args)
    {
        if (args.Length != 1)
        {
            Console.WriteLine("Usage: generateast <output_dir> | ast");
            return;
        }
        else if (!Directory.Exists(args[0]))
        {
            Console.WriteLine($"{args[0]} is an invalid directory");
            return;
        }

        string baseName = "Expr";
        List<string> types =
        [
            "Assign   : Token Name, Expr Value",
            "Binary   : Expr Left, Token Operator, Expr Right",
            "Grouping : Expr Expression",
            "Literal  : object? Value",
            "Unary    : Token Operator, Expr Right",
            "Variable : Token Name"
        ];

        DefineBase(args[0], baseName, types);
        
        baseName = "Stmt";
        types.Clear();
        types.AddRange([
            "Expression : Expr Expr",
            "Print      : Expr Expr",
            "Var        : Token Name, Expr Initializer"
        ]);

        DefineBase(args[0], baseName, types);
    }
}
