/// This file was autogenerated by LoxInterpreter/GenerateAst at 10.22.25 16:26:08.

namespace LoxInterpreter;

public abstract partial class Expr()
{

}

public partial class Binary(Expr Left, Token Operator, Expr Right) : Expr()
{
	private readonly Expr _left = Left;

	private readonly Token _operator = Operator;

	private readonly Expr _right = Right;

	public Expr Left => _left;

	public Token Operator => _operator;

	public Expr Right => _right;

}

public partial class Grouping(Expr Expression) : Expr()
{
	private readonly Expr _expression = Expression;

	public Expr Expression => _expression;

}

public partial class Literal(Object Value) : Expr()
{
	private readonly Object _value = Value;

	public Object Value => _value;

}

public partial class Unary(Token Operator, Expr Right) : Expr()
{
	private readonly Token _operator = Operator;

	private readonly Expr _right = Right;

	public Token Operator => _operator;

	public Expr Right => _right;

}

