/// This file was autogenerated by LoxInterpreter/GenerateAst at 11.07.25 11:39:39.

namespace LoxInterpreter;

public abstract partial class Stmt()
{
	public interface IVisitor
	{
		void VisitBlockStmt(Block expr);

		void VisitExpressionStmt(Expression expr);

		void VisitFunctionStmt(Function expr);

		void VisitIfStmt(If expr);

		void VisitPrintStmt(Print expr);

		void VisitReturnStmt(Return expr);

		void VisitVarStmt(Var expr);

		void VisitWhileStmt(While expr);

	}

	public abstract void Accept(IVisitor visitor);

	public partial class Block(List<Stmt> Statements) : Stmt()
	{
		private readonly List<Stmt> _statements = Statements;

		public List<Stmt> Statements => _statements;

		public override void Accept(IVisitor visitor)
		{
			visitor.VisitBlockStmt(this);
		}

	}

	public partial class Expression(Expr Expr) : Stmt()
	{
		private readonly Expr _expr = Expr;

		public Expr Expr => _expr;

		public override void Accept(IVisitor visitor)
		{
			visitor.VisitExpressionStmt(this);
		}

	}

	public partial class Function(Token Name, List<Token> Params, List<Stmt> Body) : Stmt()
	{
		private readonly Token _name = Name;

		private readonly List<Token> _params = Params;

		private readonly List<Stmt> _body = Body;

		public Token Name => _name;

		public List<Token> Params => _params;

		public List<Stmt> Body => _body;

		public override void Accept(IVisitor visitor)
		{
			visitor.VisitFunctionStmt(this);
		}

	}

	public partial class If(Expr Condition, Stmt ThenBranch, Stmt? ElseBranch) : Stmt()
	{
		private readonly Expr _condition = Condition;

		private readonly Stmt _thenbranch = ThenBranch;

		private readonly Stmt? _elsebranch = ElseBranch;

		public Expr Condition => _condition;

		public Stmt ThenBranch => _thenbranch;

		public Stmt? ElseBranch => _elsebranch;

		public override void Accept(IVisitor visitor)
		{
			visitor.VisitIfStmt(this);
		}

	}

	public partial class Print(Expr Expr) : Stmt()
	{
		private readonly Expr _expr = Expr;

		public Expr Expr => _expr;

		public override void Accept(IVisitor visitor)
		{
			visitor.VisitPrintStmt(this);
		}

	}

	public partial class Return(Token Keyword, Expr Value) : Stmt()
	{
		private readonly Token _keyword = Keyword;

		private readonly Expr _value = Value;

		public Token Keyword => _keyword;

		public Expr Value => _value;

		public override void Accept(IVisitor visitor)
		{
			visitor.VisitReturnStmt(this);
		}

	}

	public partial class Var(Token Name, Expr Initializer) : Stmt()
	{
		private readonly Token _name = Name;

		private readonly Expr _initializer = Initializer;

		public Token Name => _name;

		public Expr Initializer => _initializer;

		public override void Accept(IVisitor visitor)
		{
			visitor.VisitVarStmt(this);
		}

	}

	public partial class While(Expr Condition, Stmt Body) : Stmt()
	{
		private readonly Expr _condition = Condition;

		private readonly Stmt _body = Body;

		public Expr Condition => _condition;

		public Stmt Body => _body;

		public override void Accept(IVisitor visitor)
		{
			visitor.VisitWhileStmt(this);
		}

	}

}

