/// This file was autogenerated by LoxInterpreter/GenerateAst at 10.30.25 16:24:40.

namespace LoxInterpreter;

public abstract partial class Stmt()
{
	public interface IVisitor<T>
	{
		T VisitBlockStmt(Block expr);

		T VisitExpressionStmt(Expression expr);

		T VisitPrintStmt(Print expr);

		T VisitVarStmt(Var expr);

	}

	public abstract T Accept<T>(IVisitor<T> visitor);

	public partial class Block(List<Stmt> Statements) : Stmt()
	{
		private readonly List<Stmt> _statements = Statements;

		public List<Stmt> Statements => _statements;

		public override T Accept<T>(IVisitor<T> visitor)
		{
			return visitor.VisitBlockStmt(this);
		}

	}

	public partial class Expression(Expr Expr) : Stmt()
	{
		private readonly Expr _expr = Expr;

		public Expr Expr => _expr;

		public override T Accept<T>(IVisitor<T> visitor)
		{
			return visitor.VisitExpressionStmt(this);
		}

	}

	public partial class Print(Expr Expr) : Stmt()
	{
		private readonly Expr _expr = Expr;

		public Expr Expr => _expr;

		public override T Accept<T>(IVisitor<T> visitor)
		{
			return visitor.VisitPrintStmt(this);
		}

	}

	public partial class Var(Token Name, Expr Initializer) : Stmt()
	{
		private readonly Token _name = Name;

		private readonly Expr _initializer = Initializer;

		public Token Name => _name;

		public Expr Initializer => _initializer;

		public override T Accept<T>(IVisitor<T> visitor)
		{
			return visitor.VisitVarStmt(this);
		}

	}

}

