/// This file was autogenerated by LoxInterpreter/GenerateAst at 10.29.25 15:13:37.

namespace LoxInterpreter;

public abstract partial class Stmt()
{
	public interface IVisitor<T>
	{
		T VisitExpressionStmt(Expression expr);

		T VisitPrintStmt(Print expr);

	}

	public abstract T Accept<T>(IVisitor<T> visitor);

	public partial class Expression(Expr Expr) : Stmt()
	{
		private readonly Expr _expr = Expr;

		public Expr Expr => _expr;

		public override T Accept<T>(IVisitor<T> visitor)
		{
			return visitor.VisitExpressionStmt(this);
		}

	}

	public partial class Print(Expr Expr) : Stmt()
	{
		private readonly Expr _expr = Expr;

		public Expr Expr => _expr;

		public override T Accept<T>(IVisitor<T> visitor)
		{
			return visitor.VisitPrintStmt(this);
		}

	}

}

